### ISSUE TITLE
selenium launcher dependency causes failures when behind a firewall that blocks git protocol

### ISSUE THREAD

**Issue by oconnormi** [jmreidy/grunt-mocha-webdriver#86]
attempting to install grunt-mocha-webdriver from behind the firewall at work causes failures as the git:// protocol is blocked. attempted to use the following:

    git config --global url."https://github.com/".insteadOf git@github.com:
    git config --global url."https://".insteadOf git://
however npm still tries to pull down the dependency over git://

changing the dependency to git+https:// seems like it would resolve the problem

**Comment by jmreidy** [comment]
Moved off the Github project link to the official release
